Equipment UI
AGH-Code-Industry/monstrous-tide pull request #54
Opened 2024-01-02 14:00 UTC by Mir3605

Added equipment bar and methods to add and remove items from it. It should be enough for now, although it can be developed in the future. I didn't create nice graphics for it, as it should be done after the resolution is set to full HD.

2024-01-10 18:26 UTC, ddziechciarz requested changes
There are empty _ready and _process methods, delete them to improve code readability

2024-01-10 18:26 UTC, ddziechciarz commented on Assets/Utility/UI/Equipment/item.gd
> +func _process(delta):
get rid of all unused _ready and _process methods in all the files

2024-01-13 11:54 UTC, Mir3605 commented on Assets/Utility/UI/Equipment/item.gd
> +func _process(delta):
They were removed

2024-01-17 15:02 UTC, ddziechciarz approved these changes
git

2024-01-17 15:37 UTC, merged